name: 'HEALTHCARE_DATAMART'
version: '1.0.0'
config-version: 2

profile: 'healthcare_datamart'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  HEALTHCARE_DATAMART:
    +materialized: view

    stage:
      +schema: STAGE
      +materialized: view

    intermediate:
      +schema: INTERMEDIATE
      +materialized: view

    marts:
      +schema: MARTS
      +materialized: table
